//! # LedgerLens Score Contract
//!
//! Risk registry contract for the Veridex prediction markets platform.
//! Stores and retrieves wallet/asset-pair risk scores generated by the
//! LedgerLens off-chain fraud detection engine (Benford's Law, Tarjan SCC,
//! causal AI ensemble).
//!
//! ## Architecture
//!
//! Scores are keyed by `(wallet_address, asset_pair)` and stored as
//! [`RiskScore`] structs. Only the designated oracle authority may submit
//! scores, preventing unauthorized manipulation.
//!
//! ## Security Considerations
//!
//! - Only the admin address set at initialization can call `submit_score`.
//! - Scores contain a `submitted_at` ledger timestamp for freshness checks.
//! - Confidence is expressed as basis points (0-10000) for fixed-point safety.

#![no_std]

use soroban_sdk::{contract, contractimpl, contracttype, symbol_short, Address, Env, String};

// ---------------------------------------------------------------------------
// Storage key types
// ---------------------------------------------------------------------------

/// Composite storage key for (wallet, asset_pair) → RiskScore lookups.
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ScoreKey {
    pub wallet: Address,
    pub asset_pair: String,
}

// ---------------------------------------------------------------------------
// Data types
// ---------------------------------------------------------------------------

/// On-chain representation of a LedgerLens fraud/risk score.
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RiskScore {
    /// Wallet address being scored.
    pub wallet: Address,
    /// Asset pair identifier, e.g. "XLM/USDC".
    pub asset_pair: String,
    /// Risk score in basis points: 0 = no risk, 10000 = maximum risk.
    pub score: u32,
    /// Confidence level in basis points: 0 = no confidence, 10000 = certain.
    pub confidence: u32,
    /// Ledger timestamp at submission.
    pub submitted_at: u64,
    /// Ledger sequence number at submission (for freshness audits).
    pub ledger_sequence: u32,
}

// ---------------------------------------------------------------------------
// Contract
// ---------------------------------------------------------------------------

#[contract]
pub struct LedgerLensScore;

#[contractimpl]
impl LedgerLensScore {
    // -----------------------------------------------------------------------
    // Initialization
    // -----------------------------------------------------------------------

    /// Initialize the contract, setting `admin` as the sole authority
    /// permitted to submit scores.
    ///
    /// # Panics
    /// Panics if the contract has already been initialized.
    pub fn initialize(env: Env, admin: Address) {
        if env.storage().instance().has(&symbol_short!("ADMIN")) {
            panic!("already initialized");
        }
        env.storage()
            .instance()
            .set(&symbol_short!("ADMIN"), &admin);
    }

    // -----------------------------------------------------------------------
    // Admin management
    // -----------------------------------------------------------------------

    /// Return the current admin address.
    pub fn admin(env: Env) -> Address {
        Self::get_admin(&env)
    }

    /// Transfer admin authority to `new_admin`.
    ///
    /// Requires authorization from the current admin.
    pub fn set_admin(env: Env, new_admin: Address) {
        let current_admin = Self::get_admin(&env);
        current_admin.require_auth();
        env.storage()
            .instance()
            .set(&symbol_short!("ADMIN"), &new_admin);
    }

    // -----------------------------------------------------------------------
    // Score management
    // -----------------------------------------------------------------------

    /// Submit or update a risk score for a `(wallet, asset_pair)` pair.
    ///
    /// Only the admin may call this function. `score` and `confidence` are
    /// both expressed in basis points (0–10000).
    ///
    /// # Panics
    /// - If called by any account other than the admin.
    /// - If `score > 10000` or `confidence > 10000` (basis point overflow).
    pub fn submit_score(
        env: Env,
        wallet: Address,
        asset_pair: String,
        score: u32,
        confidence: u32,
    ) {
        // Only the oracle admin may write scores.
        let admin = Self::get_admin(&env);
        admin.require_auth();

        // Validate basis-point ranges.
        if score > 10_000 {
            panic!("score exceeds 10000 bps");
        }
        if confidence > 10_000 {
            panic!("confidence exceeds 10000 bps");
        }

        let key = ScoreKey {
            wallet: wallet.clone(),
            asset_pair: asset_pair.clone(),
        };

        let entry = RiskScore {
            wallet,
            asset_pair,
            score,
            confidence,
            submitted_at: env.ledger().timestamp(),
            ledger_sequence: env.ledger().sequence(),
        };

        env.storage().persistent().set(&key, &entry);

        // Extend TTL to ~1 year of ledger closings (assume 5s avg = 6_307_200).
        env.storage()
            .persistent()
            .extend_ttl(&key, 6_307_200, 6_307_200);
    }

    /// Retrieve the stored [`RiskScore`] for `(wallet, asset_pair)`.
    ///
    /// Returns `None` if no score has been submitted for this pair.
    pub fn get_score(env: Env, wallet: Address, asset_pair: String) -> Option<RiskScore> {
        let key = ScoreKey { wallet, asset_pair };
        env.storage().persistent().get(&key)
    }

    /// Convenience helper: return just the numeric score (bps) or `None`.
    pub fn get_score_value(env: Env, wallet: Address, asset_pair: String) -> Option<u32> {
        let key = ScoreKey { wallet, asset_pair };
        env.storage()
            .persistent()
            .get::<ScoreKey, RiskScore>(&key)
            .map(|r| r.score)
    }

    /// Return `true` if a score exists for this `(wallet, asset_pair)` pair.
    pub fn has_score(env: Env, wallet: Address, asset_pair: String) -> bool {
        let key = ScoreKey { wallet, asset_pair };
        env.storage().persistent().has(&key)
    }

    // -----------------------------------------------------------------------
    // Private helpers
    // -----------------------------------------------------------------------

    fn get_admin(env: &Env) -> Address {
        env.storage()
            .instance()
            .get::<_, Address>(&symbol_short!("ADMIN"))
            .expect("contract not initialized")
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod test {
    use super::*;
    use soroban_sdk::{testutils::Address as _, Address, Env, String};

    fn setup() -> (Env, Address, LedgerLensScoreClient<'static>) {
        let env = Env::default();
        env.mock_all_auths();
        let contract_id = env.register(LedgerLensScore, ());
        let client = LedgerLensScoreClient::new(&env, &contract_id);
        let admin = Address::generate(&env);
        client.initialize(&admin);
        (env, admin, client)
    }

    fn pair(env: &Env) -> String {
        String::from_str(env, "XLM/USDC")
    }

    // -----------------------------------------------------------------------
    // Initialization tests
    // -----------------------------------------------------------------------

    #[test]
    fn test_initialize_sets_admin() {
        let (env, admin, client) = setup();
        let stored = client.admin();
        assert_eq!(stored, admin);
        let _ = env;
    }

    #[test]
    #[should_panic(expected = "already initialized")]
    fn test_double_initialize_panics() {
        let (env, _, client) = setup();
        let another = Address::generate(&env);
        client.initialize(&another);
    }

    // -----------------------------------------------------------------------
    // Admin management tests
    // -----------------------------------------------------------------------

    #[test]
    fn test_set_admin() {
        let (env, _old_admin, client) = setup();
        let new_admin = Address::generate(&env);
        client.set_admin(&new_admin);
        assert_eq!(client.admin(), new_admin);
    }

    // -----------------------------------------------------------------------
    // Score submission tests
    // -----------------------------------------------------------------------

    #[test]
    fn test_submit_and_get_score() {
        let (env, _admin, client) = setup();
        let wallet = Address::generate(&env);
        let ap = pair(&env);

        client.submit_score(&wallet, &ap, &7500, &9000);

        let score = client.get_score(&wallet, &ap).unwrap();
        assert_eq!(score.wallet, wallet);
        assert_eq!(score.score, 7500);
        assert_eq!(score.confidence, 9000);
        assert_eq!(score.asset_pair, ap);
    }

    #[test]
    fn test_get_score_missing_returns_none() {
        let (env, _admin, client) = setup();
        let wallet = Address::generate(&env);
        let result = client.get_score(&wallet, &pair(&env));
        assert!(result.is_none());
    }

    #[test]
    fn test_has_score_false_before_submit() {
        let (env, _admin, client) = setup();
        let wallet = Address::generate(&env);
        assert!(!client.has_score(&wallet, &pair(&env)));
    }

    #[test]
    fn test_has_score_true_after_submit() {
        let (env, _admin, client) = setup();
        let wallet = Address::generate(&env);
        client.submit_score(&wallet, &pair(&env), &100, &5000);
        assert!(client.has_score(&wallet, &pair(&env)));
    }

    #[test]
    fn test_get_score_value() {
        let (env, _admin, client) = setup();
        let wallet = Address::generate(&env);
        client.submit_score(&wallet, &pair(&env), &4200, &8800);
        let val = client.get_score_value(&wallet, &pair(&env));
        assert_eq!(val, Some(4200));
    }

    #[test]
    fn test_overwrite_score() {
        let (env, _admin, client) = setup();
        let wallet = Address::generate(&env);
        let ap = pair(&env);
        client.submit_score(&wallet, &ap, &1000, &5000);
        client.submit_score(&wallet, &ap, &9999, &10000);
        let score = client.get_score(&wallet, &ap).unwrap();
        assert_eq!(score.score, 9999);
        assert_eq!(score.confidence, 10000);
    }

    #[test]
    fn test_score_zero_is_valid() {
        let (env, _admin, client) = setup();
        let wallet = Address::generate(&env);
        client.submit_score(&wallet, &pair(&env), &0, &0);
        let val = client.get_score_value(&wallet, &pair(&env));
        assert_eq!(val, Some(0));
    }

    #[test]
    fn test_score_max_boundary() {
        let (env, _admin, client) = setup();
        let wallet = Address::generate(&env);
        client.submit_score(&wallet, &pair(&env), &10000, &10000);
        let score = client.get_score(&wallet, &pair(&env)).unwrap();
        assert_eq!(score.score, 10000);
    }

    #[test]
    #[should_panic(expected = "score exceeds 10000 bps")]
    fn test_score_overflow_panics() {
        let (env, _admin, client) = setup();
        let wallet = Address::generate(&env);
        client.submit_score(&wallet, &pair(&env), &10001, &5000);
    }

    #[test]
    #[should_panic(expected = "confidence exceeds 10000 bps")]
    fn test_confidence_overflow_panics() {
        let (env, _admin, client) = setup();
        let wallet = Address::generate(&env);
        client.submit_score(&wallet, &pair(&env), &5000, &10001);
    }

    #[test]
    fn test_multiple_wallets_independent() {
        let (env, _admin, client) = setup();
        let w1 = Address::generate(&env);
        let w2 = Address::generate(&env);
        let ap = pair(&env);
        client.submit_score(&w1, &ap, &1000, &5000);
        client.submit_score(&w2, &ap, &9000, &8000);
        assert_eq!(client.get_score_value(&w1, &ap), Some(1000));
        assert_eq!(client.get_score_value(&w2, &ap), Some(9000));
    }

    #[test]
    fn test_multiple_pairs_same_wallet() {
        let (env, _admin, client) = setup();
        let wallet = Address::generate(&env);
        let ap1 = String::from_str(&env, "XLM/USDC");
        let ap2 = String::from_str(&env, "BTC/USDC");
        client.submit_score(&wallet, &ap1, &3000, &7000);
        client.submit_score(&wallet, &ap2, &8000, &6000);
        assert_eq!(client.get_score_value(&wallet, &ap1), Some(3000));
        assert_eq!(client.get_score_value(&wallet, &ap2), Some(8000));
    }
}
